name: serve
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: check pwd
        run: |
          pwd
      - name: check index
        run: |
          cat index.js
      - name: anu
        run: |
          ls
      - name: Running whatsapp
        run: |
          node ./index.js
      - name: Done! Running server 8 jam
        run: |
          bash ./serve/loop.sh
